mod bitmap;
mod block_cache;
mod block_dev;
//mod efs;
mod layout;
//mod vfs;
pub mod superblock;
pub const BLOCK_SZ: usize = 512;
//use bitmap::Bitmap;
use block_cache::{get_block_cache};
pub use block_dev::BlockDevice;
//pub use efs::EasyFileSystem;
//use layout::*;
//pub use vfs::Inode;
