[package]
name = "os"
version = "0.2.0"
authors = ["Yifan Wu<shinbokuow@163.com>", "Bowen Tang<3556495919@qq.com>", "Mengxi Feng<fmxi666@outlook.com>", "Mingjun Gao<1273938538@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [features]
# default = []  # 默认启用架构
# riscv = []    # RISC-V 支持
# loongarch = [] # LoongArch 支持

[dependencies]
bitflags = "1.2.1"
smoltcp = { version = "0.11", default-features = false, features = ["alloc", "log", "medium-ethernet", "proto-ipv4", "socket-tcp", "socket-udp", "socket-icmp", "socket-raw"] }
buddy_system_allocator = "0.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.8"
log = "0.4"
xmas-elf = "0.7.0"
zerocopy = { version = "0.8", features = ["derive"] }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
virtio-drivers = { git = "https://github.com/rcore-os/virtio-drivers", rev = "4ee80e5" }

[target.'cfg(target_arch = "loongarch64")'.dependencies]
# pci = "0.0.1" # 已经导入项目中并按规范复制许可证等
virtio-drivers-la = { package = "virtio-drivers", version = "0.12.0" } # 重命名以避免冲突

[profile.dev]
opt-level = 2
debug = 2

[profile.dev.package."*"]
opt-level = 2
