[toolchain]
profile = "minimal"
# use the nightly version of the last stable toolchain, see <https://forge.rust-lang.org/>
channel = "nightly-2026-01-01"
targets = ["riscv64gc-unknown-none-elf"]
components = ["rust-src", "llvm-tools-preview", "rustfmt", "clippy"]
